"""second

Revision ID: 6703ba661b46
Revises: ae532a73ab39
Create Date: 2025-01-10 14:28:53.082264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6703ba661b46'
down_revision = 'ae532a73ab39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('new_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_column', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
